### ISSUE TITLE
Villagers dissapered

### ISSUE THREAD

**Issue by myfbone** [froobynooby/Simple-Anti-Mob-Lag#1]
I am not sure if it's your plugin messing up. I had some named persisted noai villagers, after I install plugin they disappeared. Also I had some npcs from EliteMobs plugin, and they disappeared too. Not sure if it's connected to your plugin, but they vanished after I installed your plugin. I added villagers to 'not freeze list'.

**Comment by froobynooby** [comment]
What version is your server? If it's 1.14 or 1.14.1 then entities despawning is a vanilla bug, but you'd also notice things like item frames and armour stands despawning too. The plugin really shouldn't have an affect on the persistence of entities, since all it's really doing is changing the 'NoAI' tag.

**Comment by myfbone** [comment]
I am on 1.14.2 
Mobs from Elite mobs plug in don't have noai tag as I think, and that are disappearing every time

**Comment by froobynooby** [comment]
Are you using the latest dev build for EliteMobs? I tried using the latest release of EliteMobs from spigot and I found the same problems, both with and without SAML installed, but after I installed the dev build it seemed to work fine. You can find the latest dev releases on their discord.

There is an issue, though, with SAML removing the EliteMob NPC's NoAI tag which can cause the NPC to wander when they are supposed to stand still. But it definitely shouldn't cause them to despawn. I should be able to add something to ignore EliteMob entities so this doesn't happen

**Comment by myfbone** [comment]
I am using the latest build. This started today when I installed your plugin. But in the EliteMobs discord one guy said that it's the minecraft core bug with npc despawn, which will be fixed in 1.14.3 update. I don't know if it's my case, so I'll wait. Let you know if smth changes

**Comment by myfbone** [comment]
Actually I tested it without your plugin and all villagers restored. So it is definitely some issue with your plugin. It's very sad because I think that it is very cool and useful one, but I have to save npcs on the map. Here is my config, hope it'll help you to fix:
```
# Don't change this!
version: 5

# Do you want a config file with more options to generate?
use-advanced-config: false


# When the server's TPS drops below this, we will start freezing mobs.
tps-freezing-threshold: 16.5

# When the server's TPS rises above this, we will begin unfreezing mobs again.
# This should be higher than the tps-freezing-threshold!
tps-unfreezing-threshold: 18.0

# Every how many ticks should we freeze or unfreeze mobs? There are 20 ticks per second.
# Not recommended to set this below 600.
ticks-per-operation: 1200

# How long (in milliseconds) should the freezing or unfreezing operation be allowed to take?
# If this is set too high there may be noticeable lag spikes when we freeze mobs.
maximum-operation-time: 300

# At most how many mobs should be unfrozen in any given operation?
unfreeze-limit: 100

# Should we keep a list of chunks containing frozen mobs in them, so we may be able to unfreeze them if the plugin doesn't shut down correctly?
# Keep this as true if you think you'll uninstall this plugin at some point. This will allow you to unfreeze all the frozen mobs in your world easily.
keep-frozen-chunk-cache: true

# On startup, should we unfreeze mobs which were not unfrozen previously?
# Warning: this operation loads chunks and therefore can cause a lot of lag.
unfreeze-cached-chunks-on-startup: false

# Every how many ticks should we unfreeze these mobs?
ticks-per-cached-chunk-unfreeze: 40

# Do you use Paper? If so, do you want this task (the cache unfreezing task) to run in a more efficient manner?
use-paper-get-chunk-async: true


# Should we only freeze mobs that are in large groups, ignoring single mobs?
# This is good if you want to freeze large player-made farms, but don't want to freeze random monsters in the world.
group-bias: true

# Below what TPS should we ignore the option above and freeze EVERYTHING in accordance to the other options?
# Set to 0 to disable this option.
group-bias-tps-threshold: 7

# If there are any more than the group-minimum-size number of mobs within group-maximum-radius of each other this will constitute a group of mobs, which will be frozen if the server starts lagging.
group-minimum-size: 10
group-maximum-radius: 8.0

# Should we scale the maximum radius and minimum size required of a group depending on how much the server is lagging?
use-smart-scaling: true


# When we freeze mobs should we say so in the server console?
broadcast-to-console: true

# When we freeze mobs should we tell people with the permission 'saml.notify'?
broadcast-to-ops: false


# Should we stop mobs from targeting mobs that are frozen?
# This includes things like zombies attacking frozen villagers and baby animals following frozen adult animals.
prevent-targeting-frozen: true

# Should we stop mobs from being able to damage frozen mobs?
prevent-damaging-frozen: true

# Should we stop players from being able to damage frozen mobs?
prevent-player-damaging-frozen: false

# Should we unfreeze mobs when the chunk they are in is unloaded?
unfreeze-on-unload: true

# Should we unfreeze all the loaded mobs when the plugin shuts down?
unfreeze-on-shutdown: true

# Should we unfreeze mobs when interacted with by a player?
unfreeze-on-interact: true

# Below what TPS should we ignore the option above and not unfreeze mobs that are interacted with?
# Set to 0 to disable this option.
unfreeze-on-interact-tps-threshold: 7

# Should we unfreeze mobs when they take damage?
unfreeze-on-damage: true

# Below what TPS should we ignore the option above and not unfreeze mobs that take damage?
# Set to 0 to disable this option.
unfreeze-on-damage-tps-threshold: 0

# Should tamed mobs (cats, dogs, horses, etc.) never be frozen?
ignore-tamed: true

# Below what TPS should we ignore the option above and start freezing mobs that are tamed?
# Set to 0 to disable this option.
ignore-tamed-tps-threshold: 0

# Should we ignore mobs named with a name tag?
ignore-named: true

# Below what TPS should we ignore the option above and start freezing mobs that are named?
# Set to 0 to disable this option.
ignore-named-tps-threshold: 0

# Should mobs that are leashed never be frozen?
ignore-leashed: true

# Below what TPS should we ignore the option above and start freezing mobs that are leashed?
# Set to 0 to disable this option.
ignore-leashed-tps-threshold: 0

# Should mobs that are in love mode (breeding mode) never be frozen?
ignore-love-mode: true

# Below what TPS should we ignore the option above and start freezing mobs that are in love mode?
# Set to 0 to disable this option.
ignore-love-mode-tps-threshold: 0

# At what distance (in blocks) should we not freeze mobs that are within that distance of a player?
# Set to 0 to disable this option.
ignore-player-proximity: 0

# Below that TPS should we ignore the option above and start freezing mobs that are close to players?
# Note that this is quite an expensive check. If you have a lot of players it may make the freezing operation last significantly longer.
# Set to 0 to disable this option.
ignore-player-proximity-tps-threshold: 0


# We will never freeze mobs of this type.
# Put mobs that might be in danger if frozen here, like villagers.
# See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html for a list of types.
# This is CaSE SenSiTIVe, it needs to be in all CAPS!
never-freeze:
  - VILLAGER
  - WANDERING_TRADER
  - PILLAGER
  - VINDICATOR
  - VEX
  - WITCH
  - RAVAGER
  - ILLUSIONER
  - EVOKER

# Below what TPS should we ignore the option above and start freezing mobs on this list?
# Set to 0 to disable this option.
never-freeze-tps-threshold: 7

# If the server is lagging, we will always freeze mobs of this type. Even if they're not in a large group.
# Put mobs that are resource hogs here, like water mobs.
# See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html for a list of types.
# This is CaSE SenSiTIVe, it needs to be in all CAPS!
always-freeze:
  - COD
  - SALMON
  - TROPICAL_FISH
  - PUFFERFISH
  - TURTLE
  - SQUID
  - DOLPHIN


# We will never freeze mobs in these worlds.
ignore-world:
  - example_world_the_end
```

**Comment by myfbone** [comment]
And my assumption is that you somehow remove noai tag from villagers, and they just run away. Because as I see now, some of my villagers with noai just running freely

**Comment by froobynooby** [comment]
I've added an option to the config that allows you to completely ignore entities with specific metadata on them. EliteMobs adds metadata to their super mobs and elite mobs, so there's an option to have SAML not interfere with them.

Their NPCs do not have any metadata on them at the moment, but I asked in the dev's discord and he said he could add it. Once it has been added I will release a new version of SAML with that option set as default, but until then you'll probably just have to stop using SAML for a bit, sorry.

**Comment by myfbone** [comment]
Okay. Thx for help!

**Comment by myfbone** [comment]
And what about villagers with noai? I just summoned them by summon command. And now they are running freely. Also I summoned offencive mobs with noai and invincible, so they are problem now, because players cannot kill them and they have ai

**Comment by froobynooby** [comment]
Ah, didn't realise you summoned them yourself. I think I should be able to add an option to prevent that from happening too. I'll try to fix this tomorrow since it's quite late for me now

**Comment by myfbone** [comment]
Let me know please when you do it. I'll try to use version with this fix. Because I think that it's the same issue with npcs from elite mobs, they just run away

**Comment by froobynooby** [comment]
The plugin will now place persistent data on mobs that it freezes (i.e. data that is saved across restarts). It uses this to be able to tell if SAML froze an entity or if it was already frozen, and there's now an option 'only-unfreeze-tagged' which will mean SAML only unfreezes entities which it has frozen in the first place. This means entities summoned with the 'NoAI' tag will not be unfrozen by SAML if only-unfreeze-tagged is enabled.

One caveat to this is that any entities that were frozen prior to this new version will not have this data, and so SAML will not unfreeze them. For that reason, when your config is patched this option will be disabled by default.

I was going to test it some more before I released it on spigot as version 1.3.4 but if you'd like to use the dev build, here it is:
[SAML 1.3.4-dev1.zip](https://github.com/froobynooby/Simple-Anti-Mob-Lag/files/3297199/SAML.1.3.4-dev1.zip)

**Comment by myfbone** [comment]
Thx. I'll give it a try tomorrow

**Comment by myfbone** [comment]
I guess it's working. Neither npcs from Elite Mobs nor villagers with noai now run away. Great. Thx for quick response!
