### ISSUE TITLE
Any Tips how to lower lag spike of SAML

### ISSUE THREAD

**Issue by johnneijzen** [froobynooby/Simple-Anti-Mob-Lag#9]
before installed SAML someone had sheep farm with 60 sheep in area it was causing 1600ms ping 
![image](https://user-images.githubusercontent.com/1343960/83252708-50e1ac00-a1de-11ea-892d-6ca9a23e3b56.png)
 
then i decide to install SAML but often get lag spikes from it
https://timings.aikar.co/?id=35ea5277048d47ff8d8b5447e0c50689

**Comment by froobynooby** [comment]
The only reasons I could think of for that task to be taking as long as it is are that use-async-grouping has been disabled in the config (it's enabled by default) or ignore-player-proximity has been enabled in the config (it's disabled by default). If you haven't changed either of those options then I'm not sure what could be going on just based on timings, you'd probably need to provide me with a [spark](https://www.spigotmc.org/resources/spark.57242/) sampler report

**Comment by johnneijzen** [comment]
okay i have installed spark plugin on server i did notice that one player killed all almost all sheep in that farm so tested are timings are lot different on server i think issue fixed because that but i still give data just incase

Timings Report:
https://timings.aikar.co/?id=57b5fdca1f3245fcac9618bee10af4f1
Spark Report: ( i have do this again i just realize timings is off like lot sorry it my first time using spark)
https://spark.lucko.me/#D2hALoAQ2H
And Config File
[config.zip](https://github.com/froobynooby/Simple-Anti-Mob-Lag/files/4702126/config.zip)

**Comment by froobynooby** [comment]
Your config seems fine, but your spark report is missing a bunch of information for some reason. Could you run `/spark profiler --timeout 60` when your server is experiencing these lag spikes? Might show more info

Really strange behaviour all around, especially given sheep were also causing random spikes in that first screenshot you provided

**Comment by johnneijzen** [comment]
it quite hard to time it since lag sprike are really random but i gonna try to remove saml again and see if high sheep tick will happen again because Aikar(PaperMC developer) is also wondering where high sheep tick are from

**Comment by johnneijzen** [comment]
i have feeling this one time of thing i removed SAML to see if sheep tick will spike but it stop so i just closing this i will reopen it when it happens again
